### PR TITLE
Well wellsample image

### PR DESCRIPTION
**Pull request by will-moore**
@chris-allan I've attempted to add support for PlateAcquisition to your Wells PR.

One thing that I didn't know how to handle was the fact that 2015 schema doesn't seem to have PlateAcquisition https://www.openmicroscopy.org/Schemas/OME/2015-01/ome.xsd
I've kinda ignored this for now, but if you could point me at the strategy we've used for this elsewhere....?

This includes the ```if wellsample is None``` check which I need to handle Wells on my DB.

### CODE REVIEW

**Comment by will-moore** [comment]
Listing for standup tomorrow. cc @sbesson @jburel

**Comment by mtbc** [comment]
PlateAcquisition's in https://www.openmicroscopy.org/Schemas/SPW/2015-01/SPW.xsd

**Review by chris-allan — CHANGES_REQUESTED** [review]
As @mtbc has mentioned, PlateAcquisition was in the SPW schema in 2015-01. Documentation can be found here:

 * http://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2015-01/SPW_xsd.html#PlateAcquisition

and 2016-06:

 * http://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#PlateAcquisition

**Comment by will-moore** [comment]
@chris-allan Updated /OME/ -> /SPW/ for PlateAcquisition, and I applied the same change to Screen, Plate, Well & WellSample. Correct?

**Comment by chris-allan** [comment]
Absolutely. Thanks for catching that. Closing this PR and fast forward merging these changes into openmicroscopy/omero-marshal#31.

**Pull request closed without merging**
